### ISSUE TITLE
Username typo in github stats card

### ISSUE THREAD

**Issue by ragibalasad** [hodini007/hodini007#1]
You have misspelled your username with an extra 'o' in the github stats card in your profile readme. That's why it isn't showing anything. Fix it.

**Comment by hodini007** [comment]
Khuuje pai nai . Tui commit kore de

**Comment by ragibalasad** [comment]
Aye aye captain!

Edit: Check PR [ Fixed username typo in stats cards #2 ](https://github.com/hodini007/hodini007/pull/2)
